import Head from "next/head";
import TodoProvider from "@/context/todoContext";
import TodosList from "@/components/TodoList";
import TodoField from "@/components/TodoField";

export default function Home() {
  return (
    <>
      <Head>
        <title>Todo List App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TodoProvider>
        <main className="bg-gray-400 mb-0 pb-3 px-44">
          <TodoField />
          <TodosList />
        </main>
      </TodoProvider>
    </>
  );
}
